# Generated by Django 3.0.3 on 2021-05-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indexData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('napmpric', models.FloatField(default=0)),
                ('wagetrnd', models.FloatField(default=0)),
                ('wagetrnd_YoY', models.FloatField(default=0)),
                ('lei_totl', models.FloatField(default=0)),
                ('lei_YoY', models.FloatField(default=0)),
                ('oecd_us_YoY', models.FloatField(default=0)),
                ('oecd_total', models.FloatField(default=0)),
                ('oecd_total_Yoy', models.FloatField(default=0)),
                ('rty_YoY_spx_YoY', models.FloatField(default=0)),
                ('m2_Yoy', models.FloatField(default=0)),
                ('cycle', models.IntegerField(default=1)),
            ],
        ),
    ]
