# Generated by Django 3.0.3 on 2021-05-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdata',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
