# Generated by Django 3.0.3 on 2021-05-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiveIndexByMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('index_1', models.FloatField(default=0)),
                ('index_2', models.FloatField(default=0)),
                ('index_3', models.FloatField(default=0)),
                ('index_4', models.FloatField(default=0)),
                ('index_5', models.FloatField(default=0)),
                ('cycle', models.IntegerField(default=1)),
            ],
        ),
    ]
